# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 10:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anote_rest_apl', '0003_auto_20170212_1704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberKegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(choices=[('TS', 'Technical Staff'), ('ES', 'Engineering Staff'), ('LD', 'Leader'), ('GL', 'Group Leader'), ('PM', 'Program Manager'), ('CE', 'Chief Engineering')], default='ES', max_length=2)),
                ('kode_jabatan', models.CharField(max_length=10, verbose_name='Kode Jabatan')),
                ('kegiatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_kegiatan', to='anote_rest_apl.Kegiatan')),
                ('personil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Member Kegiatan',
                'ordering': ('kode_jabatan',),
            },
        ),
    ]
