# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anote_rest_member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberkegiatan',
            name='kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota_kegiatan', to='anote_rest_apl.Kegiatan'),
        ),
    ]
