# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anote_rest_member', '0002_auto_20170214_0556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberkegiatan',
            options={'ordering': ('order', 'kode_jabatan'), 'verbose_name_plural': 'Member Kegiatan'},
        ),
        migrations.AddField(
            model_name='memberkegiatan',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Urutan'),
        ),
    ]
