# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ButirKerekayasaan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField()),
                ('butir', models.CharField(max_length=120)),
                ('hasil', models.CharField(choices=[('LK', 'Lembar Kerja'), ('LKB', 'Lembar Kerja/Logbook'), ('LKF', 'Lembar Kerja/Foto'), ('BKL', 'Benda Kerja/Lembar Kerja'), ('LB', 'Logbook'), ('SKP', 'Surat Keputusan')], default='LK', max_length=3)),
                ('angka', models.FloatField()),
                ('pelaksana', models.CharField(choices=[('pertama', 'Perekayasa Pertama'), ('pertama_muda', 'Perekayasa Pertama/Muda'), ('muda', 'Perekayasa Muda'), ('muda_madya', 'Perekayasa Muda/Madya'), ('madya', 'Perekayasa Madya'), ('madya_utama', 'Perekayasa Madya/Utama'), ('utama', 'Perekayasa Utama'), ('semua', 'Semua Jenjang')], default='pertama', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Butir Kerekayasaan',
            },
        ),
    ]
