# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anote_rest_butir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butirkerekayasaan',
            name='hasil',
            field=models.CharField(choices=[('LK', 'Lembar Kerja'), ('LKB', 'Lembar Kerja/Logbook'), ('LKF', 'Lembar Kerja/Foto'), ('BKL', 'Benda Kerja/Lembar Kerja'), ('LB', 'Logbook'), ('SKP', 'Surat Keputusan'), ('TN', 'Technical Note')], default='LK', max_length=3),
        ),
    ]
