# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('LK', 'Lembar Kerja'), ('LB', 'Logbook')], default='LK', max_length=3)),
                ('nomor', models.CharField(max_length=255)),
                ('referensi', models.CharField(max_length=255)),
                ('tanggal', models.DateField()),
                ('butir', models.CharField(max_length=120)),
                ('angka', models.FloatField()),
                ('dibuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dibuat_oleh', to=settings.AUTH_USER_MODEL)),
                ('diketahui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diketahui_oleh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('stkk', models.CharField(max_length=255)),
                ('kode', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Kegiatan',
            },
        ),
        migrations.AddField(
            model_name='catatan',
            name='kegiatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nama_kegiatan', to='anote_rest_apl.Kegiatan'),
        ),
    ]
