# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anote_rest_apl', '0003_auto_20170212_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan',
            name='manual',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
